[project]
name = "semantic-serach-engine-free"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.2.2",
    "langchain>=1.0.2",
    "langchain-chroma>=1.0.0",
    "langchain-community>=0.4",
    "langchain-ollama>=1.0.0",
    "pypdf>=6.1.3",
    "sentence-transformers>=5.1.2",
    "streamlit>=1.50.0",
]
